apiVersion: v1
kind: PersistentVolume
metadata:
  name: telegram-compiler-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistent_volumes/telegram_compiler/storage"
